arm_variant_type: # [aarch64]
  - sbsa          # [linux and aarch64]
  - tegra         # [linux and aarch64]
c_stdlib_version:  # [linux]
  - 2.17           # [linux and aarch64]
  - 2.34           # [linux and aarch64]
zip_keys:               # [linux and aarch64]
  -                     # [linux and aarch64]
    - arm_variant_type  # [linux and aarch64]
    - c_stdlib_version  # [linux and aarch64]
